version: "3.7"

services:
  postgres:
    image: "postgres:13.1-alpine"
    environment:
      POSTGRES_PASSWORD: "compose-postgres"
      POSTGRES_USER: "compose-postgres"
    ports:
    - "5432:5432"
