export const GameClientEventType = {
    GAME_NEW: "GAME_NEW",
    GAME_NEW_STORY: "GAME_NEW_STORY",
    GAME_REVEAL: "GAME_REVEAL",
    GAME_RESET: "GAME_RESET",
    PLAYER_REGISTER: "PLAYER_REGISTER",
    PLAYER_JOIN: "PLAYER_JOIN",
    PLAYER_LEAVE: "PLAYER_LEAVE",
    VOTE_PRIVATE: "VOTE_PRIVATE",
    VOTE_PUBLIC: "VOTE_PUBLIC"
}
